[colors.primary]
background = "#232326"
foreground = "#a7aab0"

[colors.normal]
black   = "#101012"
red     = "#de5d68"
green   = "#8fb573"
yellow  = "#dbb671"
blue    = "#57a5e5"
magenta = "#bb70d2"
cyan    = "#51a8b3"
white   = "#818387"

[colors.bright]
black   = "#5a5b5e"
red     = "#de5d68"
green   = "#8fb573"
yellow  = "#dbb671"
blue    = "#57a5e5"
magenta = "#bb70d2"
cyan    = "#51a8b3"
white   = "#a7aab0"

[colors.dim]
black   = "#1b1c1e"
red     = "#833b3b"
green   = "#8fb573"
yellow  = "#7c5c20"
blue    = "#57a5e5"
magenta = "#79428a"
cyan    = "#2b5d63"
white   = "#5a5b5e"

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B[13;2u"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001B[13;5u"
