# Application bindings
$terminal = uwsm-app -- $TERMINAL
$browser = firefox 

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# Workspace switching
# Unbind all SUPER+number workspace shortcuts
unbind = SUPER, code:10
unbind = SUPER, code:11
unbind = SUPER, code:12
unbind = SUPER, code:13
unbind = SUPER, code:14
unbind = SUPER, code:15
unbind = SUPER, code:16
unbind = SUPER, code:17
unbind = SUPER, code:18
unbind = SUPER, code:19

# Create custom workpace shortcuts
bindd = SUPER, 1, Workspace 3, workspace, 3
bindd = SUPER, 2, Workspace 4, workspace, 4
bindd = SUPER, 3, Workspace 5, workspace, 5

# Hide windows
bindd = SUPER, H, Hide window, movetoworkspacesilent, 999 
bindd = SUPER SHIFT, H, Go to hidden windows, workspace, 999 

# Move focused window to workspace 1–3
bindd = SUPER SHIFT, 1, Go to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, 2, Go to workspace 4, movetoworkspace, 4
bindd = SUPER SHIFT, 3, Go to workspace 5, movetoworkspace, 5

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
