# Start numbering windows and panes at 1
set -g base-index 1
set -g pane-base-index 1

# Use Alt+number to switch windows quickly
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Optional quality of life tweaks
setw -g mode-keys vi
set -g mouse on

# Fix tmux colours
set-option -a terminal-features 'alacritty:RGB'
set -g default-terminal "tmux-256color"

# Fix Ctrl+Enter being the same as Enter
set -s extended-keys on
set -as terminal-features 'alacritty:extkeys'

# Status bar
set -g status on
set -g status-position top
set -g status-justify centre
set -g status-left ""
set -g status-right ""
set -g status-style "bg=default"

# [1][2][3] flush together, focus = bright/bold
set -g window-status-separator ""
set -g window-status-format         "#[fg=colour244][#I]"
set -g window-status-current-format "#[fg=colour15,bold][#I]"

# Kill the horizontal rule lines around the bar / panes
set -g pane-border-status off
set -g pane-border-lines single

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Restore Neovim sessions
set -g @resurrect-strategy-nvim 'session'

# Capture pane contents (scrollback) on save
set -g @resurrect-capture-pane-contents 'on'

# Auto-save every 15 min and auto-restore on tmux server start
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Keybinds
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# Save the resurrect state every time a client detaches
set-hook -g client-detached 'run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh"'

# Initialize TPM, keep this line at the very bottom of the file
run '~/.config/tmux/plugins/tpm/tpm'
